apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: app
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: backend-app # build `backend-app` image locally.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000