backend:
  image:
    repository: backend-app
    tag: latest

replicaCount: 1

env:
  REDIS_URI: "redis://redis-svc:6379"

redis:
  image:
    repository: redis
    tag: latest
  persistence:
    enabled: true
    storageClass: "standard"  # Adjust storage class according to your Kubernetes setup
    size: 8Gi               # Size of persistent storage for Redis
    accessMode: ReadWriteOnce 
  replicaCount: 1