apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: {{ .Values.replicaCount | default 1 }}  # Set replicas from values.yaml
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"  # Use values.yaml for the image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # Ensure this matches the backend's exposed port
          env:
            - name: REDIS_URI
              value: "{{ .Values.env.REDIS_URI }}"  # REDIS URI from values.yaml